[build]
  # المجلد الذي سيتم رفع ملفات الدوال منه
  functions = "netlify/functions"
  # المجلد الذي يحتوي على ملفات الموقع الثابت (هنا هو جذر المشروع)
  publish = "/" 
  
  # تعيين قواعد التحويل: توجيه المستخدمين الذين يصلون لـ php إلى html
  # هذه القواعد قد لا تكون ضرورية لكنها مفيدة لضمان التوجيه الصحيح
  # [[redirects]]
  # from = "/*.php"
  # to = "/:basename.html"
  # status = 301
